### test kafka queue
POST http://localhost:5000/insight/v1/message
Content-Type: Application/json

{
  "message": "You spent Rs.120 on ICICI bank card for starbucks coffee"
}

### create new user
POST http://localhost:3001/auth/v1/signup
Content-Type: Application/json

{
  "username": "tanishq3",
  "password": "Qwerty123@",
  "email": "t@gmail.com",
  "first_name": "tanishq",
  "last_name": "trivedi",
  "phone_number":5432456543
}